/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ipit
 */
public class karyawan extends javax.swing.JFrame 
{
int Gajian;
int Transport=70000;

private DefaultTableModel Kar;
Connection con;

private void loaddata() {
Object kolom []={"NIK", "Nama","Jenis_Kelamin", "Golongan", "Jabatan", "Absen", "Jumlah_Absen", "Biaya_Transport", "Tunjangan", "Gaji"};
Kar=new DefaultTableModel(null,kolom);
kar.setModel(Kar);
jScrollPane1.getViewport().add(kar,null);
try {
con = null;
Class.forName("com.mysql.jdbc.Driver");
Connection con =DriverManager.getConnection("jdbc:mysql://127.0.0.1/perpustakaan", "root", "");
String sql = "" + "select * from karyawan";
Statement stat=con.createStatement();
ResultSet res=stat.executeQuery(sql);
while (res.next()) {
String NIK=res.getString("NIK");
String Nama=res.getString("Nama");
String JK=res.getString("Jenis_Kelamin");
String Gol=res.getString("Golongan");
String Jab=res.getString("Jabatan");
String Abs=res.getString("Absen");
String Jml=res.getString("Jumlah_Absen");
String Transport=res.getString("Biaya_Transport");
String Tunjangan=res.getString("Tunjangan");
String Gaji=res.getString("Gaji");
Object [] data={NIK,Nama,JK,Gol,Jab,Abs,Jml,Transport,Tunjangan,Gaji};
Kar.addRow(data);}
kar.getColumnModel().getColumn(0).setPreferredWidth(50);
kar.getColumnModel().getColumn(1).setPreferredWidth(80);
kar.getColumnModel().getColumn(2).setPreferredWidth(80);
kar.getColumnModel().getColumn(3).setPreferredWidth(80);
kar.getColumnModel().getColumn(4).setPreferredWidth(80);
kar.getColumnModel().getColumn(5).setPreferredWidth(80);
kar.getColumnModel().getColumn(6).setPreferredWidth(50);
kar.getColumnModel().getColumn(7).setPreferredWidth(80);
kar.getColumnModel().getColumn(8).setPreferredWidth(80);
kar.getColumnModel().getColumn(9).setPreferredWidth(80);
} catch (Exception ex) {
JOptionPane.showMessageDialog(this, "Error: "+ex);
}
}
private void Load() {
nik.setText(null);
nama.setText(null);
jk.setText(null);
jab.setText(null);
gol.setText(null);
absen.setText("0");
jml.setText("0");
biaya.setText("0");
tunjangan.setText("0");
gaji.setText("0");
    }
    /**
     * Creates new form karyawan
     */
    public karyawan() {
        initComponents();
        setLocationRelativeTo(null);
        Load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        absen = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jml = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        biaya = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tunjangan = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        gaji = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        kar = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        gol = new javax.swing.JTextField();
        jab = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Data Karyawan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(258, 6, 229, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NIK");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 74, 81, 15);

        nik.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikActionPerformed(evt);
            }
        });
        getContentPane().add(nik);
        nik.setBounds(155, 68, 206, 21);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 101, 81, 15);

        nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(nama);
        nama.setBounds(155, 95, 206, 21);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Jabatan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 179, 81, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 128, 100, 15);

        jk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jk);
        jk.setBounds(155, 122, 206, 21);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Absen");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 70, 38, 15);

        absen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        absen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absenActionPerformed(evt);
            }
        });
        getContentPane().add(absen);
        absen.setBounds(510, 70, 206, 21);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Jumlah Absen");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 100, 85, 15);

        jml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlActionPerformed(evt);
            }
        });
        getContentPane().add(jml);
        jml.setBounds(510, 90, 206, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Biaya Transport");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 130, 96, 15);
        getContentPane().add(biaya);
        biaya.setBounds(510, 120, 206, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tunjangan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 160, 90, 15);
        getContentPane().add(tunjangan);
        tunjangan.setBounds(510, 150, 206, 22);

        search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(60, 230, 83, 22);

        edit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit);
        edit.setBounds(240, 230, 83, 22);

        save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(420, 230, 83, 22);

        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(510, 230, 79, 22);

        delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(330, 230, 79, 22);

        refresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh);
        refresh.setBounds(150, 230, 79, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Gaji");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 180, 90, 15);
        getContentPane().add(gaji);
        gaji.setBounds(510, 180, 206, 22);

        hitung.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(600, 230, 72, 22);

        kar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        kar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                karMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(kar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 270, 710, 210);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Golongan");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 155, 57, 15);

        gol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                golActionPerformed(evt);
            }
        });
        getContentPane().add(gol);
        gol.setBounds(155, 149, 206, 22);
        getContentPane().add(jab);
        jab.setBounds(155, 176, 206, 22);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raisha Afiqah\\Downloads\\a5d892f2a1b8f1e2e4fe4293676e4872.jpg")); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 740, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikActionPerformed
        // TODO add your handling code here:
        String x=nik.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn =DriverManager.getConnection("jdbc:mysql://127.0.0.1/perpustakaan", "root", "");
            Statement stat= conn.createStatement();
            String cari = "select * from karyawan where NIK='"+x+"'";
            ResultSet res=stat.executeQuery(cari);
            JOptionPane.showMessageDialog(edit, "Data ditemukan");
            loaddata();
            if (res.next()) {
                System.out.print(res.getString(1));    
                nik.setText(res.getString(1));
                nama.setText(res.getString(2));
                jk.setText(res.getString(3));
                gol.setText(res.getString(4));
                jab.setText(res.getString(5));
                absen.setText(res.getString(6));
                jml.setText(res.getString(7));
                biaya.setText(res.getString(8));
                tunjangan.setText(res.getString(9));
                gaji.setText(res.getString(8));
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ada");
            }
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_nikActionPerformed

    private void jmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String x=JOptionPane.showInputDialog(null, "Masukan  NIK!!");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn =DriverManager.getConnection("jdbc:mysql://127.0.0.1/perpustakaan", "root", "");
            Statement stat= conn.createStatement();
            String cari = "select * from karyawan where NIK='"+x+"'";
            ResultSet res=stat.executeQuery(cari);
            JOptionPane.showMessageDialog(null, "Data ditemukan");
            loaddata();
            if (res.next()) {
                System.out.print(res.getString(1));
                loaddata();
                nik.setText(res.getString(1));
                nama.setText(res.getString(2));
                jk.setText(res.getString(3));
                jab.setText(res.getString(4));
                gol.setText(res.getString(5));
                absen.setText(res.getString(6));
                jml.setText(res.getString(7));
                biaya.setText(res.getString(8));
                tunjangan.setText(res.getString(9));
                gaji.setText(res.getString(10));
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
            }
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_searchActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        int coba=JOptionPane.showConfirmDialog(null, "Yakin untuk mengubah data ini?","Confirmation",JOptionPane.YES_NO_OPTION);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn =DriverManager.getConnection("jdbc:mysql://127.0.0.1/perpustakaan", "root", "");
            String sql="update karyawan set NIK=?,Nama=?,Jenis_Kelamin=?,Jabatan=?,Golongan=?,Absen=?, Jumlah_Absen=?,Biaya_Transport=?,Tunjangan=?,Gaji=?, where "+"NIK='"+nik.getText()+"'";
            PreparedStatement st=conn.prepareStatement(sql);
            if(coba==0) {
                try {
                    st.setString(1,nik.getText());
                    st.setString(2,nama.getText());
                    st.setString(3,jk.getText());
                    st.setString(4,jab.getText());
                    st.setString(5,gol.getText());
                    st.setString(6,absen.getText());
                    st.setString(7,jml.getText());
                    st.setString(8,biaya.getText());
                    st.setString(9,tunjangan.getText());
                    st.setString(10,gaji.getText());
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Update data sukses");
                    loaddata();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Update data gagal"+e);
                }
            }
        }catch (Exception e) {}
    }//GEN-LAST:event_editActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn =DriverManager.getConnection("jdbc:mysql://127.0.0.1/perpustakaan", "root", "");
            Statement stat= conn.createStatement();
            String sqlnya=("insert into karyawan values ('"
                +nik.getText()+"','"
                +nama.getText()+"','"
                +jk.getText()+"','"
                +jab.getText()+"','"
                +gol.getText()+"','"
                +absen.getText()+"','"
                +jml.getText()+"','"
                +biaya.getText()+"','"
                +tunjangan.getText()+"','"
                +gaji.getText()+"')");
            stat.executeUpdate(sqlnya);
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
            loaddata();
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_saveActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Apakah anda ingin keluar?","Yakin", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {this.dispose();
            new menuutama().show();
        }
    }//GEN-LAST:event_exitActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String x = nik.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn =DriverManager.getConnection("jdbc:mysql://127.0.0.1/perpustakaan", "root", "");
            Statement stat= conn.createStatement();
            String sql="delete from karyawan where NIK='"+x+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data telah dihapus");
            loaddata();
            nik.setText(null);
            nama.setText(null);
            jk.setText(null);
            jab.setText(null);
            gol.setText(null);
            absen.setText(null);
            jml.setText(null);
            biaya.setText(null);
            tunjangan.setText(null);
            gaji.setText(null);
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal"+e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        Load();
    }//GEN-LAST:event_refreshActionPerformed

    private void golActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_golActionPerformed
        // TODO add your handling code here:
    int golongan=Integer.parseInt(gol.getText());
    switch (golongan) {
        case 1:
        jab.setText("Manager");
        tunjangan.setText("700000");
        break;
        case 2:
        jab.setText("Supervisor");
        tunjangan.setText("500000");
        break;
        case 3:
        jab.setText("Staff");
        tunjangan.setText("300000");
        break;
        case 4:
        jab.setText("ass staff");
        tunjangan.setText("250000");
        break;
        case 5:
        jab.setText("Honorer");
        tunjangan.setText("200000");
        break;
        default:
        JOptionPane.showMessageDialog(null, "Maaf Anda salah input, silakan pilih 1-5");
        jab.setText("");
        gaji.setText("");
    }
    }//GEN-LAST:event_golActionPerformed

    private void absenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absenActionPerformed
        // TODO add your handling code here:
    int a=Integer.parseInt(absen.getText());
    int x=a+Integer.parseInt(jab.getText());
    jab.setText(""+x);
    int c=Integer.parseInt(biaya.getText());
    int y=x*Transport;
    biaya.setText(""+y);
    }//GEN-LAST:event_absenActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
    int Golongan=Integer.parseInt(gol.getText());
    int Btrans=Integer.parseInt(biaya.getText());
    int Tunjangan=Integer.parseInt(tunjangan.getText());
    int Y=Btrans+Tunjangan+Gajian;
    if(Golongan==1) {
    Gajian=2000000;
    gaji.setText(""+Y);
    } else if (Golongan==2) {
    Gajian=1500000;
    gaji.setText(""+Y);
    } else if (Golongan==3) {
    Gajian=1000000;
    gaji.setText(""+Y);
    } else if (Golongan==4) {
    Gajian=750000;
    gaji.setText(""+Y);
    } else if (Golongan==5) {
    Gajian=500000;
    gaji.setText(""+Y);
    }
    }//GEN-LAST:event_hitungActionPerformed

    private void karMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karMouseClicked
        // TODO add your handling code here:
    int i = kar.getSelectedRow(); 
    if(i==-1){ return; } 
    String code = (String)kar.getValueAt(i,0); 
    String code1 = (String)kar.getValueAt(i,1); 
    String code2 = (String)kar.getValueAt(i,2); 
    String code3 = (String)kar.getValueAt(i,3); 
    String code4 = (String)kar.getValueAt(i,4);
    String code5 = (String)kar.getValueAt(i,5);
    String code6 = (String)kar.getValueAt(i,6);
    String code7 = (String)kar.getValueAt(i,7);
    String code8 = (String)kar.getValueAt(i,8);
    String code9 = (String)kar.getValueAt(i,9);
    nik.setText(code); 
    nama.setText(code1); 
    jk.setText(code2); 
    gol.setText(code3); 
    jab.setText(code4);
    absen.setText(code5);
    jml.setText(code6);
    biaya.setText(code7);
    tunjangan.setText(code8);
    gaji.setText(code9);
    }//GEN-LAST:event_karMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField absen;
    private javax.swing.JTextField biaya;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JTextField gaji;
    private javax.swing.JTextField gol;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jab;
    private javax.swing.JTextField jk;
    private javax.swing.JTextField jml;
    private javax.swing.JTable kar;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nik;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTextField tunjangan;
    // End of variables declaration//GEN-END:variables

}

