/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ipit
 */
public class transaksi extends javax.swing.JFrame {
Connection conn;
Statement stat;
ResultSet res;
Connection con;

    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
        koneksi();
        loaddata();
        loaddata1();
    }
    
    private void loaddata() {
    DefaultTableModel t= new DefaultTableModel();
    t.addColumn("Kode_Buku");
    t.addColumn("Nama_Buku");
    t.addColumn("Nama_Pengarang");
    t.addColumn("Penerbit");
    t.addColumn("Tahun_Terbit");
    tabuk.setModel (t); 
    try{ res=stat.executeQuery("Select * from data_buku");
    while (res.next()) {
    t.addRow (new Object [] 
    {res.getString("Kode_Buku"),
    res.getString("Nama_Buku"),
    res.getString("Nama_Pengarang"),
    res.getString("Penerbit"),
    res.getString("Tahun_Terbit")
    });
    }
    } catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, e);
    }
    }
    
    private void koneksi() {
try {
Class.forName("com.mysql.jdbc.Driver");
conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1/database_perpustakaan", "root", "");
stat=conn.createStatement();
} catch (Exception e) {
JOptionPane.showMessageDialog(null, e);
}
}
    
    private void loaddata1() {
   DefaultTableModel t= new DefaultTableModel();
    t.addColumn("NIM");
    t.addColumn("Nama"); 
    t.addColumn("KodeBuku");
    t.addColumn("NamaBuku");
    t.addColumn("TanggalPeminjaman");
    t.addColumn("TanggalPengembalian");
    peminjam.setModel (t); 
    try{ res=stat.executeQuery("Select * from peminjam");
    while (res.next()) {
    t.addRow (new Object []
    {res.getString("NIM"),
    res.getString("Nama"),
    res.getString("KodeBuku"),
    res.getString("NamaBuku"),
    res.getString("TanggalPeminjaman"),
    res.getString("TanggalPengembalian")
    });
    }
    } catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, e);
    }
}    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        kodebuku = new javax.swing.JTextField();
        namabuku = new javax.swing.JTextField();
        nim = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tglp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabuk = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        peminjam = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        tglk = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIM");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(23, 72, 68, 15);

        refresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh);
        refresh.setBounds(503, 69, 77, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(23, 105, 93, 15);

        delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(503, 103, 79, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal Pinjam");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(23, 225, 110, 15);

        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(503, 137, 79, 22);

        kodebuku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(kodebuku);
        kodebuku.setBounds(148, 141, 204, 21);

        namabuku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(namabuku);
        namabuku.setBounds(148, 180, 204, 21);

        nim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(nim);
        nim.setBounds(148, 69, 204, 21);

        nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(nama);
        nama.setBounds(148, 102, 204, 21);

        search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(402, 69, 83, 22);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Peminjaman Buku");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(226, 6, 320, 44);

        tglp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tglp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglpActionPerformed(evt);
            }
        });
        getContentPane().add(tglp);
        tglp.setBounds(149, 222, 204, 21);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Buku");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(23, 141, 68, 15);

        edit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit);
        edit.setBounds(402, 103, 83, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Buku");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(23, 183, 77, 15);

        save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(402, 137, 83, 22);

        tabuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabuk);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(625, 104, 571, 444);

        peminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        peminjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peminjamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(peminjam);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(23, 364, 580, 184);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal Kembali");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(23, 263, 120, 15);

        tglk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tglk);
        tglk.setBounds(149, 260, 204, 21);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Tabel Data Buku");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(625, 69, 121, 23);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tabel Data Peminjam");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(23, 329, 159, 23);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raisha Afiqah\\Downloads\\download.jpeg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 610, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        nim.setText(null);
        nama.setText(null);
        kodebuku.setText(null);
        namabuku.setText(null);
        tglp.setText(null);
        tglk.setText(null);
    }//GEN-LAST:event_refreshActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
    String x = kodebuku.getText();
    try {
    String sql="delete from peminjam where KodeBuku='"+x+"'";
    stat.executeUpdate(sql);
    JOptionPane.showMessageDialog(null, "Data telah dihapus");
    loaddata1();
    nim.setText(null);
    nama.setText(null);
    kodebuku.setText(null);
    namabuku.setText(null);
    tglp.setText(null);
    tglk.setText(null);
    } catch (Exception e) {
    System.out.print(e);
    JOptionPane.showMessageDialog(null, "Koneksi Gagal");
    }

    }//GEN-LAST:event_deleteActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Apakah anda ingin keluar?","Yakin", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {this.dispose();
            new menuutama().show();
        }
    }//GEN-LAST:event_exitActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String x=JOptionPane.showInputDialog(null, "Masukan  Kode Buku!!");
        try { 
            String cari = "select * from peminjam where KodeBuku='"+x+"'";
            res=stat.executeQuery(cari);
            if (res.next()) {
                System.out.print(res.getString(1));
                JOptionPane.showMessageDialog(null, "Peminjam ditemukan");
                nim.setText(res.getString("NIM"));
                nama.setText(res.getString("Nama"));
                kodebuku.setText(res.getString("Kode_Buku"));
                namabuku.setText(res.getString("Nama_Buku"));
                tglp.setText(res.getString("Tanggal_Peminjaman"));
                tglk.setText(res.getString("Tanggal_Pengembalian"));
                loaddata1();
            } else {
                JOptionPane.showMessageDialog(null, "Buku Belum Dipinjam");
            }
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_searchActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_editActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try {
    stat.executeUpdate("insert into peminjam values ("
    + "'" + nim.getText ()+"',"
    + "'" + nama.getText ()+"',"
    + "'" + kodebuku.getText ()+"',"
    + "'" + namabuku.getText ()+"',"
    + "'" + tglp.getText ()+"',"
    + "'" + tglk.getText()+"')");
    loaddata1();
    JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
    } catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Perintah Salah: "+e);
    }
    }//GEN-LAST:event_saveActionPerformed

    private void tabukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabukMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tabukMouseClicked

    
    
    private void peminjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamMouseClicked
        // TODO add your handling code here:
    int i = peminjam.getSelectedRow(); 
    if(i==-1){ return; } 
    String code = (String)peminjam.getValueAt(i,0); 
    String code1 = (String)peminjam.getValueAt(i,1); 
    String code2 = (String)peminjam.getValueAt(i,2); 
    String code3 = (String)peminjam.getValueAt(i,3); 
    String code4 = (String)peminjam.getValueAt(i,4);
    String code5 = (String)peminjam.getValueAt(i,5);
    nim.setText(code); 
    nama.setText(code1); 
    kodebuku.setText(code2); 
    namabuku.setText(code3); 
    tglp.setText(code4);
    tglk.setText(code5);
    }//GEN-LAST:event_peminjamMouseClicked

    private void tglpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglpActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_tglpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kodebuku;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField namabuku;
    private javax.swing.JTextField nim;
    private javax.swing.JTable peminjam;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTable tabuk;
    private javax.swing.JTextField tglk;
    private javax.swing.JTextField tglp;
    // End of variables declaration//GEN-END:variables

    
}
